// packages/vue/src/components/UserProfile.vue
<template>
  <div v-if="isLoading">
    <slot name="loading">
      <div>Loading profile...</div>
    </slot>
  </div>

  <div v-else-if="!isAuthenticated || !user">
    <slot name="fallback" />
  </div>

  <div v-else :class="profileClass">
    <slot :user="user">
      <!-- Default profile display -->
      <div class="user-profile">
        <img 
          v-if="showAvatar && user.profilePicture"
          :src="user.profilePicture"
          :alt="user.name || 'User avatar'"
          :style="{ width: '40px', height: '40px', borderRadius: '50%' }"
          class="user-avatar"
        />
        
        <div v-if="showName && user.name" class="user-name">
          {{ user.name }}
        </div>
        
        <div v-if="showEmail && user.email" class="user-email">
          {{ user.email }}
        </div>
        
        <div v-if="showRoles && user.roles && user.roles.length > 0" class="user-roles">
          <span 
            v-for="role in user.roles" 
            :key="role" 
            class="user-role"
          >
            {{ role }}
          </span>
        </div>
      </div>
    </slot>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useAuth } from '../composables/useAuth';

interface Props {
  showAvatar?: boolean;
  showEmail?: boolean;
  showName?: boolean;
  showRoles?: boolean;
  class?: string | string[] | Record<string, boolean>;
}

const props = withDefaults(defineProps<Props>(), {
  showAvatar: true,
  showEmail: true,
  showName: true,
  showRoles: false,
  class: '',
});

const auth = useAuth();

const profileClass = computed(() => {
  const classes = [];
  
  if (typeof props.class === 'string') {
    classes.push(props.class);
  } else if (Array.isArray(props.class)) {
    classes.push(...props.class);
  } else if (typeof props.class === 'object') {
    for (const [key, value] of Object.entries(props.class)) {
      if (value) classes.push(key);
    }
  }
  
  return classes.join(' ');
});

// Computed properties from auth state
const { isLoading, isAuthenticated, user } = auth;
</script>

<style scoped>
.user-profile {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.user-avatar {
  align-self: flex-start;
}

.user-name {
  font-weight: 500;
}

.user-email {
  color: #6b7280;
  font-size: 0.875rem;
}

.user-roles {
  display: flex;
  gap: 8px;
  flex-wrap: wrap;
}

.user-role {
  background-color: #f3f4f6;
  color: #374151;
  padding: 2px 8px;
  border-radius: 12px;
  font-size: 0.75rem;
  font-weight: 500;
}
</style>

// packages/react/src/components/UserProfile.tsx
import { ReactNode } from 'react';
import { useAuth } from '../hooks/useAuth';
import { UserInfo } from '../types';

interface UserProfileProps {
  children?: (user: UserInfo) => ReactNode;
  fallback?: ReactNode;
  showAvatar?: boolean;
  showEmail?: boolean;
  showName?: boolean;
  showRoles?: boolean;
  className?: string;
}

export function UserProfile({
  children,
  fallback,
  showAvatar = true,
  showEmail = true,
  showName = true,
  showRoles = false,
  className,
}: UserProfileProps) {
  const { isAuthenticated, user, isLoading } = useAuth();

  if (isLoading) {
    return fallback || <div>Loading profile...</div>;
  }

  if (!isAuthenticated || !user) {
    return fallback || null;
  }

  // If children is a function, use render prop pattern
  if (typeof children === 'function') {
    return <>{children(user)}</>;
  }

  // Default profile display
  return (
    <div className={className}>
      {showAvatar && user.profilePicture && (
        <img
          src={user.profilePicture}
          alt={user.name || 'User avatar'}
          style={{ width: 40, height: 40, borderRadius: '50%' }}
        />
      )}
      
      {showName && user.name && (
        <div className="user-name">{user.name}</div>
      )}
      
      {showEmail && user.email && (
        <div className="user-email">{user.email}</div>
      )}
      
      {showRoles && user.roles && user.roles.length > 0 && (
        <div className="user-roles">
          {user.roles.map(role => (
            <span key={role} className="user-role">
              {role}
            </span>
          ))}
        </div>
      )}
    </div>
  );
}

interface UserAvatarProps {
  size?: number;
  fallback?: ReactNode;
  className?: string;
  onClick?: () => void;
}

export function UserAvatar({ size = 40, fallback, className, onClick }: UserAvatarProps) {
  const { user, isAuthenticated } = useAuth();

  if (!isAuthenticated || !user) {
    return fallback || null;
  }

  const avatarStyle = {
    width: size,
    height: size,
    borderRadius: '50%',
    cursor: onClick ? 'pointer' : 'default',
  };

  if (user.profilePicture) {
    return (
      <img
        src={user.profilePicture}
        alt={user.name || 'User avatar'}
        style={avatarStyle}
        className={className}
        onClick={onClick}
      />
    );
  }

  // Fallback to initials
  const initials = user.name
    ? user.name
        .split(' ')
        .map(n => n[0])
        .join('')
        .toUpperCase()
        .slice(0, 2)
    : user.email?.[0]?.toUpperCase() || '?';

  return (
    <div
      style={{
        ...avatarStyle,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#f0f0f0',
        color: '#333',
        fontSize: size * 0.4,
        fontWeight: 'bold',
      }}
      className={className}
      onClick={onClick}
    >
      {initials}
    </div>
  );
}

interface UserNameProps {
  fallback?: ReactNode;
  className?: string;
}

export function UserName({ fallback, className }: UserNameProps) {
  const { user, isAuthenticated } = useAuth();

  if (!isAuthenticated || !user || !user.name) {
    return fallback || null;
  }

  return <span className={className}>{user.name}</span>;
}

interface UserEmailProps {
  fallback?: ReactNode;
  className?: string;
}

export function UserEmail({ fallback, className }: UserEmailProps) {
  const { user, isAuthenticated } = useAuth();

  if (!isAuthenticated || !user || !user.email) {
    return fallback || null;
  }

  return <span className={className}>{user.email}</span>;
}
