// packages/react/src/components/AuthGuard.tsx
import { ReactNode } from 'react';
import { useAuth } from '../hooks/useAuth';

interface AuthGuardProps {
  children: ReactNode;
  fallback?: ReactNode;
  requiredRoles?: string[];
  requireAllRoles?: boolean;
  onUnauthorized?: () => void;
  redirectTo?: string;
}

export function AuthGuard({
  children,
  fallback,
  requiredRoles = [],
  requireAllRoles = false,
  onUnauthorized,
  redirectTo,
}: AuthGuardProps) {
  const { isLoading, isAuthenticated, user } = useAuth();

  // Show loading state
  if (isLoading) {
    return fallback || <div>Loading...</div>;
  }

  // Not authenticated
  if (!isAuthenticated) {
    if (redirectTo) {
      window.location.href = redirectTo;
      return null;
    }
    
    if (onUnauthorized) {
      onUnauthorized();
    }
    
    return fallback || <div>Authentication required</div>;
  }

  // Check role requirements
  if (requiredRoles.length > 0 && user) {
    const userRoles = user.roles || [];
    
    const hasRequiredRoles = requireAllRoles
      ? requiredRoles.every(role => userRoles.includes(role))
      : requiredRoles.some(role => userRoles.includes(role));

    if (!hasRequiredRoles) {
      if (onUnauthorized) {
        onUnauthorized();
      }
      
      return fallback || <div>Insufficient permissions</div>;
    }
  }

  // All checks passed
  return <>{children}</>;
}

interface RequireAuthProps {
  children: ReactNode;
  fallback?: ReactNode;
}

export function RequireAuth({ children, fallback }: RequireAuthProps) {
  return (
    <AuthGuard fallback={fallback}>
      {children}
    </AuthGuard>
  );
}

interface RequireRolesProps {
  children: ReactNode;
  roles: string[];
  requireAll?: boolean;
  fallback?: ReactNode;
}

export function RequireRoles({ 
  children, 
  roles, 
  requireAll = false, 
  fallback 
}: RequireRolesProps) {
  return (
    <AuthGuard 
      requiredRoles={roles}
      requireAllRoles={requireAll}
      fallback={fallback}
    >
      {children}
    </AuthGuard>
  );
}

// packages/vue/src/components/AuthGuard.vue
<template>
  <div v-if="isLoading">
    <slot name="loading">
      <div>Loading...</div>
    </slot>
  </div>

  <div v-else-if="!isAuthenticated">
    <slot name="fallback">
      <div>Authentication required</div>
    </slot>
  </div>

  <div v-else-if="!hasRequiredRoles">
    <slot name="unauthorized">
      <div>Insufficient permissions</div>
    </slot>
  </div>

  <div v-else>
    <slot />
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted } from 'vue';
import { useAuth } from '../composables/useAuth';

interface Props {
  requiredRoles?: string[];
  requireAllRoles?: boolean;
  onUnauthorized?: () => void;
  redirectTo?: string;
}

const props = withDefaults(defineProps<Props>(), {
  requiredRoles: () => [],
  requireAllRoles: false,
});

const auth = useAuth();
const { isAuthenticated, isLoading, user } = auth;

const hasRequiredRoles = computed(() => {
  if (props.requiredRoles.length === 0 || !user.value) {
    return true;
  }
  
  const userRoles = (user.value as any)?.roles || [];
  
  return props.requireAllRoles
    ? props.requiredRoles.every(role => userRoles.includes(role))
    : props.requiredRoles.some(role => userRoles.includes(role));
});

onMounted(() => {
  if (!isLoading.value && !isAuthenticated.value) {
    if (props.redirectTo) {
      window.location.href = props.redirectTo;
      return;
    }
    
    props.onUnauthorized?.();
  }
  
  if (!isLoading.value && isAuthenticated.value && !hasRequiredRoles.value) {
    props.onUnauthorized?.();
  }
});
</script>
